# Лабораторная работа 1 #

Импортировать NumPy под именем np

In [1]:
import numpy as np

Напечатать версию и конфигурацию

In [2]:
print(np.version.version)
np.show_config()

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [4]:
arr2 = np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [5]:
arr3 = np.array([2.5 for i in range(10)])
print(arr3)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Как получить документацию о функции numpy.add из командной строки?

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [6]:
arr4 = np.zeros(10)
arr4[4] = 1
print(arr4)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор со значениями от 10 до 49

In [7]:
arr5 = np.arange(10, 50)
print(arr5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Развернуть вектор (первый становится последним)

In [8]:
arr6 = arr5[::-1]
print(arr6)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [9]:
arr7 = np.arange(9).reshape(3,3)
print(arr7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [10]:
arr8 = np.nonzero([1,2,0,0,4,0])
print(arr8)

(array([0, 1, 4], dtype=int32),)


Создать массив 3x3x3 со случайными значениями

In [11]:
arr9 = np.random.random((3,3,3))
print(arr9)

[[[0.24280756 0.27496062 0.85564367]
  [0.09495674 0.00643213 0.33800973]
  [0.6129682  0.0214594  0.6622206 ]]

 [[0.88888751 0.23220584 0.8626969 ]
  [0.066249   0.54671776 0.54763596]
  [0.79086177 0.4135676  0.52372402]]

 [[0.91962289 0.29310519 0.1545927 ]
  [0.33895024 0.37317853 0.17210341]
  [0.91192594 0.55454898 0.64093543]]]


Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [12]:
arr10 = np.random.random((10,10))
print(arr10)
print(arr10.max())
print(arr10.min())

[[0.06798769 0.62556552 0.52773955 0.20962198 0.24830812 0.45055622
  0.28740559 0.69503532 0.237023   0.58769763]
 [0.65862226 0.76883808 0.46855574 0.95706923 0.40811345 0.46564623
  0.40309477 0.62190302 0.18147616 0.71961296]
 [0.3075174  0.44175762 0.41444534 0.25689616 0.55208315 0.46584211
  0.10510094 0.86363169 0.59118763 0.77008503]
 [0.11384211 0.32259229 0.11035138 0.78031578 0.8428498  0.47147272
  0.96324839 0.89132095 0.92004799 0.70873486]
 [0.49104962 0.22978806 0.27235027 0.53273427 0.94772123 0.38714987
  0.86432494 0.14715977 0.10761176 0.11444426]
 [0.97878292 0.92584937 0.04402148 0.33279744 0.66002183 0.3586852
  0.61807619 0.87670647 0.53639849 0.74351357]
 [0.13290626 0.92013187 0.47756369 0.29507548 0.19569238 0.80638999
  0.70012581 0.56553533 0.59088386 0.9599436 ]
 [0.58125718 0.0977487  0.8848681  0.73681265 0.50789356 0.57746201
  0.28485556 0.24248058 0.41067268 0.46549951]
 [0.24087827 0.74319115 0.46157153 0.18726026 0.32977612 0.54791169
  0.19493212 

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [13]:
arr11 = np.random.random(30)
print(arr11)
avg = np.average(arr11)
print(avg)

[0.94247803 0.63040263 0.68454034 0.27280504 0.2305914  0.17045323
 0.84228356 0.17023236 0.30928041 0.54734118 0.43507326 0.38880361
 0.44962758 0.89895924 0.20243488 0.80233086 0.63415519 0.31780537
 0.58138155 0.38236014 0.44111284 0.79364387 0.88245602 0.58119309
 0.66461005 0.77595861 0.77067974 0.48874525 0.12178902 0.04004067]
0.5151189662846107


Создать матрицу с 0 внутри, и 1 на границах

In [14]:
arr12 = np.ones((20,20))
arr12[1:-1,1:-1] = 0
print(arr12)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

Выяснить результат следующих выражений<br/>
0 * np.nan<br/>
np.nan == np.nan<br/>
np.inf > np.nan<br/>
np.nan - np.nan<br/>

In [15]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [16]:
arr13 = np.diag(np.arange(1, 5), k=-1)
print(arr13)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Создать 8x8 матрицу и заполнить её в шахматном порядке

In [17]:
arr14 = np.zeros((8,8))
arr14[::2, ::2]=1
arr14[1::2,1::2]=1
print(arr14)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [18]:
index = np.unravel_index(100, (6, 7, 8))
print(index)

(1, 5, 4)


Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [20]:
arr15 = np.tile(np.array([np.tile([1,0],4), np.tile([0,1],4)]),[4,1])
print(arr15)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
