# Лабораторная работа 2 #

Перемножить матрицы 5x3 и 3x2

In [1]:
import numpy as np

arr1 = np.ones((5,3))
arr2 = np.ones((3,2))
arr3 = np.dot(arr1,arr2)
print(arr1)
print(arr2)
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr4 = np.arange(20)
arr4[(arr4 >= 3) & (arr4 <= 8)] *=-1
print(arr4)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


Создать 5x5 матрицу со значениями в строках от 0 до 4

In [3]:
arr5 = np.zeros((5,5))
arr5 += np.arange(5)
print(arr5)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Есть генератор, сделать с его помощью массив

In [4]:
def generator():
    for x in range(10):
        yield x
        
arr6 = np.fromiter(generator(),dtype=int)
print(arr6)

[0 1 2 3 4 5 6 7 8 9]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [5]:
arr7 = np.linspace(0,1,12)[1:-1]
print(arr7)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Отсортировать вектор

In [6]:
arr8  = np.random.random(20)
print(arr8)
arr8.sort()
print(arr8)

[0.84719362 0.06033899 0.59537334 0.71910977 0.44827837 0.84176799
 0.05379991 0.90246719 0.26284642 0.32762729 0.1093673  0.5836178
 0.91098805 0.22756558 0.98215449 0.19372526 0.03000638 0.28328111
 0.60212279 0.60711402]
[0.03000638 0.05379991 0.06033899 0.1093673  0.19372526 0.22756558
 0.26284642 0.28328111 0.32762729 0.44827837 0.5836178  0.59537334
 0.60212279 0.60711402 0.71910977 0.84176799 0.84719362 0.90246719
 0.91098805 0.98215449]


Проверить, одинаковы ли 2 numpy массива

In [7]:
arr9 = np.ones(9)
arr10 = np.ones(9)

print(np.allclose(arr9,arr10))
arr10[1]=0
print(np.allclose(arr9,arr10))

True
False


Сделать массив неизменяемым

In [8]:
arr11 = np.arange(10)
arr11.flags.writeable = False
print(arr11)
arr11[0]=10

[0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [ ]:
arr12 = np.random.random((10,2))
arr12_x = arr12[:,0]
arr12_y = arr12[:,1]

arr12_range = np.hypot(arr12_x, arr12_y)
arr12_angle = np.arctan2(arr12_y,arr12_x)
print(arr12_range)
print(arr12_angle)

Заменить максимальный элемент на ноль

In [ ]:
arr13 = np.random.random(20)
print(arr13)
arr13[arr13.argmax()]=0
print(arr13)

Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [9]:
arr14 = np.zeros((10,10), [('x',float),('y',float)])
arr14['x'], arr14['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(arr14)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [10]:
arr15_x = np.arange(5)
arr15_y = arr15_x + np.random.random()+1
arr15_c =  1.0 / np.subtract.outer(arr15_x, arr15_y)
print(arr15_x)
print(arr15_y)
print(arr15_c)

[0 1 2 3 4]
[1.37171401 2.37171401 3.37171401 4.37171401 5.37171401]
[[-0.72901493 -0.421636   -0.29658506 -0.22874323 -0.18616032]
 [-2.69024024 -0.72901493 -0.421636   -0.29658506 -0.22874323]
 [ 1.59163187 -2.69024024 -0.72901493 -0.421636   -0.29658506]
 [ 0.61414273  1.59163187 -2.69024024 -0.72901493 -0.421636  ]
 [ 0.3804761   0.61414273  1.59163187 -2.69024024 -0.72901493]]


Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [11]:
for datatype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(datatype).min)
   print(np.iinfo(datatype).max)
   print()
for datatype in [np.float32, np.float64]:
   print(np.finfo(datatype).min)
   print(np.finfo(datatype).max)
   print(np.finfo(datatype).eps)
   print()

-128
127

-2147483648
2147483647

-9223372036854775808
9223372036854775807

-3.4028235e+38
3.4028235e+38
1.1920929e-07

-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16



Напечатать все значения в массиве

In [12]:
arr16 = np.random.randint(0,1000,1001)
print(arr16)
np.set_printoptions(threshold=float('inf'))
print(arr16)

[123 506 116 ... 409 966 652]
[123 506 116 520 149 470 543 787 378  50 308  96 882 119 360 820 122 221
 363 524 774 794  77 928  62 731 550 539 371 216 529 973 562 584 810 654
 121  50 497 112 201 114 200 117 302  72  85 956 947 587  93 425   3 147
 487 610 906 877 361 771 593 185 404 796 293 393 860 161 573  15 911  51
 439  93 201 334 926 866  46 432 450 572 752 699  30 998 205  14 887 795
 142 484 870   4 697   6   8 921 260 447 893 255 475 425  76 253  97 474
 551 685 545 730 514 817 112 901 733 675 585  22 475 623 121 644 381 907
 157 144 355 936 129 404 170 743 752 740 371 732 140 462 875 551 679 506
 241 481  21 585 592 288 326 162 828 582 378 532 209 159 100 812 898 847
 418 329  60 594 581 673  72 526 201 445 357 512 311 949 613 309  69 949
 435 422 974 726 756 290 770 660 722  96 889 680 113 430 950 661  10 387
 763 434 601 617 317 623 744 257 546 848 201 718 339 827 280 877 356 589
 769 459 379  28 715 125 534 277 875 956 941 358 549 340  57 410 105 347
 740 948 267  31 555 

Найти ближайшее к заданному значению число в заданном массиве

In [20]:
arr17 = np.arange(100)
rundom_number = np.random.uniform(0,100)
print(arr17)
print(rundom_number)
print(arr17[(np.abs(arr17-rundom_number)).argmin()])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
91.57480489008918
92


Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [21]:
arr18 = np.zeros(10, 
                     [ ('coordinate', [ ('x', int), ('y', int)]),
                       ('color',      [ ('r', int), ('g', int), ('b', int)])
                     ]
                )
print(arr18)

[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0))]


Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [23]:
import scipy.spatial

arr19 = np.random.random((5,2))
print(arr19)
arr20 = scipy.spatial.distance.cdist(arr19,arr19)
print(arr20)

[[0.70694292 0.74599283]
 [0.23063114 0.99453929]
 [0.14838511 0.0198741 ]
 [0.81205817 0.89776734]
 [0.23918405 0.93010164]]
[[0.         0.53725994 0.91609783 0.18462047 0.50268719]
 [0.53725994 0.         0.97812916 0.58942531 0.06500279]
 [0.91609783 0.97812916 0.         1.10052646 0.91474512]
 [0.18462047 0.58942531 1.10052646 0.         0.5737859 ]
 [0.50268719 0.06500279 0.91474512 0.5737859  0.        ]]


Преобразовать массив из float в int

In [24]:
arr21 = np.arange(10, dtype=np.int32)
print(arr21)
arr21 = arr21.astype(np.float32, copy=False)
print(arr21)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Дан файл:<br/>
1,2,3,4,5<br/>
6,,,7,8<br/>
,,9,10,11<br/>
Как прочитать его?


In [25]:
#arr = np.genfromtxt("data.txt", delimiter=",")

Каков эквивалент функции enumerate для numpy массивов?


In [50]:
arr22 = np.random.randint(0,16, 16)
for key, value in enumerate(arr22):
    print(key, value)
print()
#вариант 1
for key, value in np.ndenumerate(arr22):
    print(key, value)
print()
#вариант 2
for key in np.ndindex(arr22.shape):
    print(key, arr22[key])

0 12
1 8
2 12
3 6
4 13
5 3
6 4
7 12
8 3
9 7
10 7
11 0
12 1
13 3
14 5
15 6

(0,) 12
(1,) 8
(2,) 12
(3,) 6
(4,) 13
(5,) 3
(6,) 4
(7,) 12
(8,) 3
(9,) 7
(10,) 7
(11,) 0
(12,) 1
(13,) 3
(14,) 5
(15,) 6

(0,) 12
(1,) 8
(2,) 12
(3,) 6
(4,) 13
(5,) 3
(6,) 4
(7,) 12
(8,) 3
(9,) 7
(10,) 7
(11,) 0
(12,) 1
(13,) 3
(14,) 5
(15,) 6


Сформировать 2D массив с распределением Гаусса


In [64]:
arr23, arr24 = np.meshgrid(np.linspace(-1,1,6), np.linspace(-1,1,6))
arr25 = np.hypot(arr23, arr24)
SIGMA, MU = 1.0, 0.0
arr26 = 1/(SIGMA*(2*np.pi)**0.5)*np.exp(-((arr25 - MU) ** 2 / (2.0 * SIGMA ** 2)))
print(arr26)

[[0.14676266 0.20211094 0.23717938 0.23717938 0.20211094 0.14676266]
 [0.20211094 0.27833258 0.32662631 0.32662631 0.27833258 0.20211094]
 [0.23717938 0.32662631 0.38329953 0.38329953 0.32662631 0.23717938]
 [0.23717938 0.32662631 0.38329953 0.38329953 0.32662631 0.23717938]
 [0.20211094 0.27833258 0.32662631 0.32662631 0.27833258 0.20211094]
 [0.14676266 0.20211094 0.23717938 0.23717938 0.20211094 0.14676266]]


Случайно расположить p элементов в 2D массив


In [66]:
n = 10
p = 3
arr27 = np.zeros((n,n))
np.put(arr27, np.random.choice(range(n*n), p, replace=False), 1)
print(arr27)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Отнять среднее из каждой строки в матрице


In [74]:
arr28 = np.random.rand(3, 6)
print(arr28)
arr28_row_avg = arr28.mean(axis=1, keepdims=True)
print(arr28_row_avg)
arr29 = arr28 - arr28_row_avg
print(arr29)

[[0.5199685  0.72462213 0.28552997 0.20110564 0.72714297 0.51649784]
 [0.3645882  0.09862924 0.37162265 0.76870495 0.31116735 0.11794867]
 [0.85562997 0.35355684 0.58788258 0.98081939 0.04141265 0.04705479]]
[[0.49581117]
 [0.33877684]
 [0.47772604]]
[[ 0.02415732  0.22881096 -0.2102812  -0.29470553  0.23133179  0.02068666]
 [ 0.02581136 -0.24014761  0.03284581  0.42992811 -0.0276095  -0.22082817]
 [ 0.37790393 -0.1241692   0.11015654  0.50309335 -0.43631338 -0.43067125]]


Отсортировать матрицу по n-ому столбцу


In [80]:
arr30 = np.random.randint(0,10,(5,5))
n = 0  
print(arr30)
print(arr30[arr30[:,n].argsort()])

[[2 1 0 2 2]
 [8 1 5 7 2]
 [6 9 0 3 0]
 [2 0 3 3 5]
 [4 4 2 3 9]]
[[2 1 0 2 2]
 [2 0 3 3 5]
 [4 4 2 3 9]
 [6 9 0 3 0]
 [8 1 5 7 2]]


Определить, есть ли в 2D массиве нулевые столбцы


In [88]:
arr31 = np.random.randint(0,3,(3,10))
print(arr31)
print((~arr31.any(axis=0)).any())

[[0 2 1 0 0 0 1 2 2 0]
 [0 0 1 2 1 1 1 0 1 2]
 [0 0 0 2 1 2 1 0 0 0]]
True


Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)


In [98]:
arr32 = np.ones(10)
arr33 = np.random.randint(0,len(arr32),9)
print(arr33)
arr32 += np.bincount(arr33, minlength=len(arr32))
print(arr32)

[7 6 2 6 7 0 1 6 5]
[2. 2. 2. 1. 1. 2. 4. 3. 1. 1.]


Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов


In [111]:
w,h = 4,4
arr34 = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)

arr35 = arr34[...,0] * 2 * 2 + arr34[...,1] * 2 + arr34[...,2]
print(arr34)
print(arr35)
print(len(np.unique(arr35)))

[[[0 0 0]
  [1 1 0]
  [0 0 1]
  [0 1 0]]

 [[0 0 1]
  [1 0 0]
  [0 0 0]
  [0 1 0]]

 [[0 0 1]
  [0 0 0]
  [1 1 1]
  [1 0 0]]

 [[0 1 0]
  [0 0 0]
  [1 1 1]
  [1 1 0]]]
[[0 6 1 2]
 [1 4 0 2]
 [1 0 7 4]
 [2 0 7 6]]
6


Дан четырехмерный массив, посчитать сумму по последним двум осям


In [127]:
arr36 = np.random.randint(0,10, (3,2,2,4))
print(arr36)
print(arr36.reshape(arr36.shape[:-2] + (-1,)).sum(axis=-1))

[[[[3 7 2 9]
   [5 1 9 7]]

  [[6 5 2 3]
   [7 4 5 9]]]


 [[[3 4 1 5]
   [8 0 8 2]]

  [[9 7 6 1]
   [1 9 6 8]]]


 [[[0 0 5 6]
   [3 3 6 6]]

  [[9 3 5 1]
   [9 5 2 3]]]]
[[43 41]
 [31 47]
 [29 37]]


Найти диагональные элементы произведения матриц

In [91]:
arr37 = np.random.randint(0,3, (5,3))
arr38 = np.random.randint(0,3, (3,5))
print(arr37)
print(arr38)
print(np.diag(np.dot(arr37, arr38)))

[[0 1 1]
 [0 0 2]
 [2 0 2]
 [0 0 1]
 [0 2 0]]
[[0 0 2 2 0]
 [1 1 1 2 0]
 [1 0 2 1 2]]
[2 0 8 1 0]
