---
                                            Московский Авиационный Институт  
                                      (Национальный Исследовательский Университет)  
        
                
                
    Кафедра 806 «Вычислительная математика и программирование»  
    Институт: «Информационные технологии и прикладная математика»  
    Дисциплина: «Разработка ПО для высокопроизводительных систем»        
                


                                            -------------------------------
                                            Лабораторная работа по NumPy №2  
                                            -------------------------------    
                                            
                                            
                                            
                                                                                Группа: М8О-103М-20  
                                                                                Студент: Винников Алексей Владимирович  
                                                                                Преподаватель: Поповкин Александр Викторович  
                                                                                
                                                                                
                                                                                
                                                     Москва, 2020  
                                                         
---

Перемножить матрицы 5x3 и 3x2

In [1]:
import numpy as np

arr1 = np.ones((5,3))
arr2 = np.ones((3,2))
arr3 = np.dot(arr1,arr2)
print(arr1)
print(arr2)
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr4 = np.arange(20)
arr4[(arr4 >= 3) & (arr4 <= 8)] *=-1
print(arr4)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


Создать 5x5 матрицу со значениями в строках от 0 до 4

In [3]:
arr5 = np.zeros((5,5))
arr5 += np.arange(5)
print(arr5)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Есть генератор, сделать с его помощью массив

In [4]:
def generator():
    for x in range(10):
        yield x
        
arr6 = np.fromiter(generator(),dtype=int)
print(arr6)

[0 1 2 3 4 5 6 7 8 9]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [5]:
arr7 = np.linspace(0,1,12)[1:-1]
print(arr7)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Отсортировать вектор

In [6]:
arr8  = np.random.random(20)
print(arr8)
arr8.sort()
print(arr8)

[0.43457614 0.10990276 0.91368832 0.71716187 0.75392594 0.90494152
 0.10263227 0.24448471 0.1829717  0.96344544 0.83715719 0.45290532
 0.71549845 0.38098623 0.25967245 0.98285939 0.53139288 0.90840604
 0.27886651 0.32394589]
[0.10263227 0.10990276 0.1829717  0.24448471 0.25967245 0.27886651
 0.32394589 0.38098623 0.43457614 0.45290532 0.53139288 0.71549845
 0.71716187 0.75392594 0.83715719 0.90494152 0.90840604 0.91368832
 0.96344544 0.98285939]


Проверить, одинаковы ли 2 numpy массива

In [7]:
arr9 = np.ones(9)
arr10 = np.ones(9)

print(np.allclose(arr9,arr10))
arr10[1]=0
print(np.allclose(arr9,arr10))

True
False


Сделать массив неизменяемым

In [8]:
arr11 = np.arange(10)
arr11.flags.writeable = False
print(arr11)
arr11[0]=10

[0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [9]:
arr12 = np.random.random((10,2))
arr12_x = arr12[:,0]
arr12_y = arr12[:,1]

arr12_range = np.hypot(arr12_x, arr12_y)
arr12_angle = np.arctan2(arr12_y,arr12_x)
print(arr12_range)
print(arr12_angle)

[0.9421301  0.18726464 0.98137026 0.80037857 0.7116877  1.15165686
 1.09325519 0.3692858  0.56815401 1.30282777]
[1.35262085 1.05054309 0.88775991 1.36999159 1.29220906 0.86062449
 0.5824916  0.96396048 0.47779601 0.71762728]


Заменить максимальный элемент на ноль

In [10]:
arr13 = np.random.random(20)
print(arr13)
arr13[arr13.argmax()]=0
print(arr13)

[0.47291029 0.06019734 0.82537574 0.26558127 0.45942802 0.00523608
 0.23935177 0.88377391 0.25780959 0.37693296 0.42123818 0.34602373
 0.31998718 0.98674448 0.13986108 0.50252611 0.74336163 0.96695546
 0.12414594 0.55122678]
[0.47291029 0.06019734 0.82537574 0.26558127 0.45942802 0.00523608
 0.23935177 0.88377391 0.25780959 0.37693296 0.42123818 0.34602373
 0.31998718 0.         0.13986108 0.50252611 0.74336163 0.96695546
 0.12414594 0.55122678]


Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [11]:
arr14 = np.zeros((10,10), [('x',float),('y',float)])
arr14['x'], arr14['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(arr14)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [12]:
arr15_x = np.arange(5)
arr15_y = arr15_x + np.random.random()+1
arr15_c =  1.0 / np.subtract.outer(arr15_x, arr15_y)
print(arr15_x)
print(arr15_y)
print(arr15_c)

[0 1 2 3 4]
[1.33104917 2.33104917 3.33104917 4.33104917 5.33104917]
[[-0.75128704 -0.42899138 -0.30020572 -0.23089094 -0.18758034]
 [-3.02069927 -0.75128704 -0.42899138 -0.30020572 -0.23089094]
 [ 1.49487819 -3.02069927 -0.75128704 -0.42899138 -0.30020572]
 [ 0.59917883  1.49487819 -3.02069927 -0.75128704 -0.42899138]
 [ 0.37467907  0.59917883  1.49487819 -3.02069927 -0.75128704]]


Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [13]:
for datatype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(datatype).min)
   print(np.iinfo(datatype).max)
   print()
for datatype in [np.float32, np.float64]:
   print(np.finfo(datatype).min)
   print(np.finfo(datatype).max)
   print(np.finfo(datatype).eps)
   print()

-128
127

-2147483648
2147483647

-9223372036854775808
9223372036854775807

-3.4028235e+38
3.4028235e+38
1.1920929e-07

-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16



Напечатать все значения в массиве

In [14]:
arr16 = np.random.randint(0,1000,1001)
print(arr16)
np.set_printoptions(threshold=float('inf'))
print(arr16)

[295 639 797 ...   9 794 442]
[295 639 797 437 363 782 244  89 473 170   6  23 844 170 159 361 308 402
 987 359 263 521 764 545 267 384 265 911 740 424 319 114  97 732 930 104
 938  25 414 627 728 584   7 959 972 983 801 175 488 470 603 827 189 298
 154 351 253 464 764 230 880 854 270 326 563 776 880 325 114 344 167 687
 851  19  99 880 330 905 683 940 457 570 610 290 912 949 828 459  48 577
 613 452 141 476 735  66 379 763 897 625 965 669 417  84 653 876 399 153
 737 969 585 593 283 601 608 743 751 850 689   6 372  29 644 977 825 111
  67 546 621 320 354 903 344  30  47  48 858 399 445 171 131 316 646 448
 761 783 895 442 331  42  23 911  34 696 959 817 502 214 637 906  83 386
 458 803 859 477 414 175 915 866 145 751 725 937 477 299 994 212 336 390
 844 471 181 952 295 472 383 479 270 164 356 179 858 765 217 698 361 838
 928 999 317 183 791 293 633 349 279 645 615 226 485 697 597 167 541 106
 739 190 815 435 133 863 427 911 373 882  21 549  87 691 747 428 669 916
 965 882 126 428 100 

Найти ближайшее к заданному значению число в заданном массиве

In [15]:
arr17 = np.arange(100)
random_number = np.random.uniform(0,100)
print(arr17)
print(random_number)
print(arr17[(np.abs(arr17-random_number)).argmin()])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
75.31829842119676
75


Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [16]:
arr18 = np.zeros(10, 
                     [ ('coordinate', [ ('x', int), ('y', int)]),
                       ('color',      [ ('r', int), ('g', int), ('b', int)])
                     ]
                )
print(arr18)

[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0))]


Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [17]:
import scipy.spatial

arr19 = np.random.random((5,2))
print(arr19)
arr20 = scipy.spatial.distance.cdist(arr19,arr19)
print(arr20)

[[0.22810543 0.30735906]
 [0.28531038 0.08495954]
 [0.12976102 0.25439051]
 [0.15516414 0.98373433]
 [0.60547551 0.16686454]]
[[0.         0.22963874 0.11170179 0.68029694 0.40267468]
 [0.22963874 0.         0.23000534 0.90814875 0.33047563]
 [0.11170179 0.23000534 0.         0.72978607 0.48369937]
 [0.68029694 0.90814875 0.72978607 0.         0.93276824]
 [0.40267468 0.33047563 0.48369937 0.93276824 0.        ]]


Преобразовать массив из float в int

In [18]:
arr21 = np.arange(10, dtype=np.int32)
print(arr21)
arr21 = arr21.astype(np.float32, copy=False)
print(arr21)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Дан файл:<br/>
1,2,3,4,5<br/>
6,,,7,8<br/>
,,9,10,11<br/>
Как прочитать его?


In [19]:
#arr = np.genfromtxt("data.txt", delimiter=",")

Каков эквивалент функции enumerate для numpy массивов?


In [20]:
arr22 = np.random.randint(0,16, 16)
for key, value in enumerate(arr22):
    print(key, value)
print()
#вариант 1
for key, value in np.ndenumerate(arr22):
    print(key, value)
print()
#вариант 2
for key in np.ndindex(arr22.shape):
    print(key, arr22[key])

0 2
1 5
2 8
3 13
4 0
5 6
6 7
7 15
8 13
9 5
10 6
11 3
12 14
13 14
14 10
15 5

(0,) 2
(1,) 5
(2,) 8
(3,) 13
(4,) 0
(5,) 6
(6,) 7
(7,) 15
(8,) 13
(9,) 5
(10,) 6
(11,) 3
(12,) 14
(13,) 14
(14,) 10
(15,) 5

(0,) 2
(1,) 5
(2,) 8
(3,) 13
(4,) 0
(5,) 6
(6,) 7
(7,) 15
(8,) 13
(9,) 5
(10,) 6
(11,) 3
(12,) 14
(13,) 14
(14,) 10
(15,) 5


Сформировать 2D массив с распределением Гаусса


In [21]:
arr23, arr24 = np.meshgrid(np.linspace(-1,1,6), np.linspace(-1,1,6))
arr25 = np.hypot(arr23, arr24)
SIGMA, MU = 1.0, 0.0
arr26 = 1/(SIGMA*(2*np.pi)**0.5)*np.exp(-((arr25 - MU) ** 2 / (2.0 * SIGMA ** 2)))
print(arr26)

[[0.14676266 0.20211094 0.23717938 0.23717938 0.20211094 0.14676266]
 [0.20211094 0.27833258 0.32662631 0.32662631 0.27833258 0.20211094]
 [0.23717938 0.32662631 0.38329953 0.38329953 0.32662631 0.23717938]
 [0.23717938 0.32662631 0.38329953 0.38329953 0.32662631 0.23717938]
 [0.20211094 0.27833258 0.32662631 0.32662631 0.27833258 0.20211094]
 [0.14676266 0.20211094 0.23717938 0.23717938 0.20211094 0.14676266]]


Случайно расположить p элементов в 2D массив


In [22]:
n = 10
p = 3
arr27 = np.zeros((n,n))
np.put(arr27, np.random.choice(range(n*n), p, replace=False), 1)
print(arr27)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Отнять среднее из каждой строки в матрице


In [32]:
arr28 = np.random.rand(3, 6)
print(arr28)
arr28_row_avg = arr28.mean(axis=1, keepdims=True)
print(arr28_row_avg)
arr29 = arr28 - arr28_row_avg
print(arr29)

[[0.74810995 0.85737338 0.4014509  0.04527028 0.82873483 0.19370536]
 [0.18703578 0.10217987 0.48590676 0.16356206 0.62323365 0.45843688]
 [0.96741423 0.46524921 0.7872295  0.01344169 0.98183531 0.72337103]]
[[0.51244079]
 [0.33672584]
 [0.6564235 ]]
[[ 0.23566916  0.3449326  -0.11098988 -0.4671705   0.31629405 -0.31873543]
 [-0.14969005 -0.23454596  0.14918093 -0.17316378  0.28650782  0.12171105]
 [ 0.31099074 -0.19117429  0.13080601 -0.64298181  0.32541182  0.06694753]]


Отсортировать матрицу по n-ому столбцу


In [24]:
arr30 = np.random.randint(0,10,(5,5))
n = 0  
print(arr30)
print(arr30[arr30[:,n].argsort()])

[[4 1 2 0 2]
 [5 1 6 6 9]
 [2 2 2 7 9]
 [6 2 6 9 9]
 [3 7 9 2 0]]
[[2 2 2 7 9]
 [3 7 9 2 0]
 [4 1 2 0 2]
 [5 1 6 6 9]
 [6 2 6 9 9]]


Определить, есть ли в 2D массиве нулевые столбцы


In [25]:
arr31 = np.random.randint(0,3,(3,10))
print(arr31)
print((~arr31.any(axis=0)).any())

[[1 1 1 1 0 1 1 1 0 0]
 [1 0 0 1 0 2 1 1 1 0]
 [1 2 2 2 0 0 2 2 0 0]]
True


Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)


In [26]:
arr32 = np.ones(10)
arr33 = np.random.randint(0,len(arr32),9)
print(arr33)
arr32 += np.bincount(arr33, minlength=len(arr32))
print(arr32)

[9 0 1 2 4 3 3 6 0]
[3. 2. 2. 3. 2. 1. 2. 1. 1. 2.]


Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов


In [27]:
w,h = 4,4
arr34 = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)

arr35 = arr34[...,0] * 2 * 2 + arr34[...,1] * 2 + arr34[...,2]
print(arr34)
print(arr35)
print(len(np.unique(arr35)))

[[[0 1 1]
  [0 0 0]
  [0 0 0]
  [1 0 1]]

 [[0 1 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 1 1]
  [1 0 0]
  [1 0 1]
  [0 1 0]]

 [[0 1 1]
  [1 1 0]
  [1 1 0]
  [0 0 0]]]
[[3 0 0 5]
 [2 0 0 0]
 [3 4 5 2]
 [3 6 6 0]]
6


Дан четырехмерный массив, посчитать сумму по последним двум осям


In [28]:
arr36 = np.random.randint(0,10, (3,2,2,4))
print(arr36)
print(arr36.reshape(arr36.shape[:-2] + (-1,)).sum(axis=-1))

[[[[9 5 9 5]
   [0 2 6 7]]

  [[9 9 9 7]
   [3 5 1 7]]]


 [[[6 0 6 5]
   [9 7 3 6]]

  [[7 0 2 5]
   [5 3 2 5]]]


 [[[1 9 1 1]
   [1 4 0 7]]

  [[7 1 5 4]
   [8 5 3 5]]]]
[[43 50]
 [42 29]
 [24 38]]


Найти диагональные элементы произведения матриц

In [29]:
arr37 = np.random.randint(0,3, (5,3))
arr38 = np.random.randint(0,3, (3,5))
print(arr37)
print(arr38)
print(np.diag(np.dot(arr37, arr38)))

[[1 0 0]
 [0 1 0]
 [2 2 0]
 [1 2 0]
 [2 0 0]]
[[1 2 1 0 2]
 [0 0 1 1 2]
 [0 2 0 1 0]]
[1 0 4 2 4]
