# Лабораторная работа 3 #

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.zeros(len(arr1) + (len(arr1)-1)*(3))
arr2[::4] = arr1
print(arr2)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Поменять 2 строки в матрице

In [2]:
arr3 = np.arange(25).reshape(5,5)
arr3[[0,1]] = arr3[[1,0]]
print(arr3)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [3]:
triangles = np.random.randint(0,100,(10,3))
print(triangles)
#повторяем дважды каждый элемент массива и сдвигаем влево на 1
temp = np.roll(triangles.repeat(2,axis=1),-1,axis=1)
pairs = temp.reshape(len(temp)*3,2)
#сортируем пары точек (отрезки) от большего к меньшему
pairs = np.sort(pairs,axis=1)
pairs = pairs.view( dtype=[('x0',pairs.dtype),('x1',pairs.dtype)] )
pairs = np.unique(pairs)
print(pairs)

[[68  4 97]
 [59 99 37]
 [91 45 52]
 [81 69 83]
 [64 85 22]
 [58 57 85]
 [38 54 58]
 [93  2 87]
 [35 14 37]
 [44 53 46]]
[( 2, 87) ( 2, 93) ( 4, 68) ( 4, 97) (14, 35) (14, 37) (22, 64) (22, 85)
 (35, 37) (37, 59) (37, 99) (38, 54) (38, 58) (44, 46) (44, 53) (45, 52)
 (45, 91) (46, 53) (52, 91) (54, 58) (57, 58) (57, 85) (58, 85) (59, 99)
 (64, 85) (68, 97) (69, 81) (69, 83) (81, 83) (87, 93)]


Дан массив C; создать массив A, что np.bincount(A) == C

In [4]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


Посчитать среднее, используя плавающее окно(скользящее среднее)

In [5]:
arr4 = np.arange(20)
width = 2
arr5 = np.cumsum(arr4, dtype=float)
arr5[width:] = arr5[width:] - arr5[:-width]
result = arr5[width-1:] / width
print(result)

[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5
 14.5 15.5 16.5 17.5 18.5]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [6]:
from numpy.lib import stride_tricks

Z = np.arange(13)
width = 3
arr6 = stride_tricks.as_strided(Z, shape=(Z.size - width + 1, width), strides=(4, 4));
print(arr6)

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]]


Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [7]:
arr7 = np.random.randint(0,2,20)
print(arr7)
np.logical_not(arr7, out=arr7)
print(arr7)

[0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0]
[1 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 1]


Посчитать ранг матрицы

In [8]:
arr8 = np.random.randint(0,2,(4,4))
print(arr8)
rank = np.linalg.matrix_rank(arr8)
print(rank)

[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 1 1]]
3


Найти наиболее частое значение в массиве

In [9]:
arr9 = np.random.randint(0,10,50)
print(arr9)
print(np.bincount(arr9).argmax())

[1 0 7 2 0 0 7 3 2 9 1 9 2 9 9 2 9 4 0 1 7 8 9 5 1 6 0 3 3 5 7 1 2 1 7 7 4
 1 7 3 9 4 3 9 4 5 3 6 8 6]
9


Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [10]:
arr10 = np.random.randint(0,5,(4,4))
dim = 3

arr11 = stride_tricks.as_strided(
    arr10, 
    shape=(arr10.shape[0] - dim + 1, arr10.shape[1] - dim + 1, dim, dim), 
    strides=arr10.strides + arr10.strides
)
print(arr10)
print(arr11)

[[1 0 0 0]
 [3 0 2 1]
 [4 0 0 2]
 [4 1 2 4]]
[[[[1 0 0]
   [3 0 2]
   [4 0 0]]

  [[0 0 0]
   [0 2 1]
   [0 0 2]]]


 [[[3 0 2]
   [4 0 0]
   [4 1 2]]

  [[0 2 1]
   [0 0 2]
   [1 2 4]]]]


Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [11]:
p, n = 5, 10
arr11_matrix= np.ones((p,n,n))
arr11_vector = np.ones((p,n,))
print(np.einsum('ijk,ik->k', arr11_matrix, arr11_vector))

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


Дан массив 16x16, посчитать сумму по блокам 4x4

In [12]:
arr12 = np.ones((16,16), dtype=np.int8)
dim = 4
arr12_result = np.sum(stride_tricks.as_strided(
    arr12, 
    shape=(arr12.shape[0] - dim + 1, arr10.shape[1] - dim + 1, dim, dim), 
    strides=arr12.strides + arr10.strides
), axis = (-2,-1))
print(arr12_result)

[[16]
 [16]
 [16]
 [16]
 [16]
 [16]
 [16]
 [16]
 [16]
 [16]
 [16]
 [16]
 [16]]


Найти n наибольших значений в массиве

In [13]:
n = 5
arr13 = np.random.randint(0,100,100)
print (arr13[np.argpartition(-arr13, n)][:n])

[95 93 98 93 96]


Построить прямое произведение массивов (все комбинации с каждым элементом)

In [14]:
arrays = [1, 2, 3, 21], [4, 5], [6, 7], [1]

arrays = [np.asarray(a) for a in arrays]
grid = np.indices(map(len, arrays), dtype=int)
grid = grid.reshape(len(arrays), -1).T

for n, arr in enumerate(arrays):
    grid[:, n] = arrays[n][grid[:, n]]
        
print(grid)


[[ 1  4  6  1]
 [ 1  4  7  1]
 [ 1  5  6  1]
 [ 1  5  7  1]
 [ 2  4  6  1]
 [ 2  4  7  1]
 [ 2  5  6  1]
 [ 2  5  7  1]
 [ 3  4  6  1]
 [ 3  4  7  1]
 [ 3  5  6  1]
 [ 3  5  7  1]
 [21  4  6  1]
 [21  4  7  1]
 [21  5  6  1]
 [21  5  7  1]]


Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [15]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)

rows = np.argwhere(np.prod(np.sum((A[..., np.newaxis, np.newaxis] == B), dtype=bool, axis=(-3,-1)), dtype=bool, axis=-1) == True)
rows = rows.reshape((rows.shape[0],))
print(A[rows])

[[0 4 0]
 [4 0 1]
 [0 0 0]
 [3 0 0]
 [3 3 2]
 [0 3 3]
 [0 1 0]
 [1 3 1]]
[[1 0]
 [4 2]]
[[0 4 0]
 [4 0 1]]


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [16]:
arr21 = np.random.randint(0,3,(10,3))
print(arr21)
result = arr21[~np.logical_and.reduce(arr21[:,1:] == arr21[:,:-1], axis=1)]
print(result)

[[0 0 1]
 [1 0 2]
 [2 0 1]
 [1 2 2]
 [1 0 0]
 [1 2 2]
 [1 1 1]
 [0 2 2]
 [0 2 0]
 [0 0 0]]
[[0 0 1]
 [1 0 2]
 [2 0 1]
 [1 2 2]
 [1 0 0]
 [1 2 2]
 [0 2 2]
 [0 2 0]]


Преобразовать вектор чисел в матрицу бинарных представлений

In [17]:
arr22 = np.random.randint(0,10, 8, dtype=np.uint8)
print(arr22)
print(np.unpackbits(arr22[..., np.newaxis], axis=1))

[7 9 0 9 5 6 5 4]
[[0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 0 0]]


Дан двумерный массив. Найти все различные строки

In [18]:
arr23 = np.random.randint(0, 2, (8,3))
print(arr23)
print(np.unique(arr23,axis=0))

[[0 0 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 0 0]
 [1 1 1]
 [0 1 0]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [19]:
arr24 = np.random.randint(0, 10, 5)
arr25 = np.random.randint(0, 10, 5)

print(arr24)
print(arr25)
print("sum", end="\n")
print(np.einsum('i->', arr24))
print(np.sum(arr24))
print("mul", end="\n")       
print(np.einsum('i,i->i', arr24, arr25))
print(np.multiply(arr24, arr25))
print("inner", end="\n")        
print(np.einsum('i,i->', arr24, arr25)) 
print(np.inner(arr24, arr25))
print("outer", end="\n")      
print(np.einsum('i,j->ij', arr24, arr25)) 
print(np.outer(arr24, arr25))   

[9 8 1 4 6]
[9 9 7 2 9]
sum
28
28
mul
[81 72  7  8 54]
[81 72  7  8 54]
inner
222
222
outer
[[81 81 63 18 81]
 [72 72 56 16 72]
 [ 9  9  7  2  9]
 [36 36 28  8 36]
 [54 54 42 12 54]]
[[81 81 63 18 81]
 [72 72 56 16 72]
 [ 9  9  7  2  9]
 [36 36 28  8 36]
 [54 54 42 12 54]]
